/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "leveldb_constants.h"

namespace LevelDB {

const leveldbConstants g_leveldb_constants;

leveldbConstants::leveldbConstants() {
}

} // namespace

