/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef leveldb_CONSTANTS_H
#define leveldb_CONSTANTS_H

#include "leveldb_types.h"

namespace LevelDB {

class leveldbConstants {
 public:
  leveldbConstants();

};

extern const leveldbConstants g_leveldb_constants;

} // namespace

#endif
